version: "3.12"

networks:
  backend:
    driver: bridge

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5433:5432"
    networks:
      - "backend"

  backend:
    build: ./backend/api/
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/api/:/backend/
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    networks:
      - "backend"

  frontend:
    build: ./frontend/
    container_name: angular_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - "backend"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
        reservations:
          cpus: "0.5"
          memory: "256M"
